Matris Oluşturma ve İşlemler:

In [1]:
import numpy as np 

In [2]:
#3x3 boyutunda rastgele tamsayılardan oluşan bir NumPy matrisi oluşturun.
matrix=np.random.rand(3,3)
print(matrix)

[[0.6658513  0.86237956 0.35610817]
 [0.12808627 0.61453678 0.69337533]
 [0.28567998 0.82925437 0.95355752]]


In [3]:
#Transpozesini alın.
matrix_transpose=matrix.T
print("matrix transpose'i =",matrix_transpose)

matrix transpose'i = [[0.6658513  0.12808627 0.28567998]
 [0.86237956 0.61453678 0.82925437]
 [0.35610817 0.69337533 0.95355752]]


In [4]:
#Determinantını hesaplayın. 
matrix_det=np.linalg.det(matrix)
print("matrix'in determinat'i =",matrix_det)

matrix'in determinat'i = 0.04813201060448518


In [5]:
#matrix'in her eleman 2 ile çarpımı
print(matrix*2)

[[1.33170261 1.72475911 0.71221633]
 [0.25617254 1.22907356 1.38675066]
 [0.57135997 1.65850874 1.90711504]]
