    Diziler

In [ ]:
#altbaşlıklar
#-NumPy array'leri oluşturma
#-Built-in Functionlarla Hızlıca NumPy Arrayleri Oluşturma
#-Rasgele diziler oluşturma
#-Arrayin Boyut Sayısını ve Shape'ini Kontrol Etmek
#Dizi kopyalarken dikkat!!!
#Dosyadan dizi yükleme


In [2]:
import numpy as np

NumPy array'leri oluşturma

In [ ]:

#Arrayler çok boyutlu diziler gibi düşünebilir.
#Arraylerin boyutları(dimension) vardır. 0d,1d,2d,3d,4d.... 

#Arrayleri oluşturmanın 3 farklı yolu vardır. 
# 1) liste ya da tuble benzeri nesneleri array'e döndürebiliriz.        np.array([1,2,3])
# 2)Built-in hazır fonksiyonlar yardımıyla arrayler oluşturabiliiriz.   np.arrange(), np.linspace(), np.logspace vb.
# 3)Rasgele data üreterek.                                              np.random modülünün içindeki fonksiyonlar yarddımıyla.

In [ ]:
arr0d=np.array(53)
print(arr0d)

53


In [ ]:
arr1d=np.array([1,2,3,4])
print(arr1d)

[1 2 3 4]


In [ ]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr3d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[100,200,300]]])
print(arr3d)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [100 200 300]]]


In [ ]:
print(arr3d[0][0][0])

1


Built-in Functionlarla Hızlıca NumPy Arrayleri Oluşturma

In [ ]:
#np.arange() fonksiyonu ile hızlıca arrayler oluşturabiliriz. istediğimiz sayı aralığında ardışık artan arrayler oluştururuz. 
#kullanımı aynen range() gibi. start point dahil, End point dahil değil. 
#Gene aynı range() fonsiyonunda olduğu gibi (start-stop-step parametrelerini alır.)

In [ ]:
np.array([1,2,3,4,5,6,7,8,9])

[1 2 3 4 5 6 7 8 9]


In [ ]:
np.arange(1,10)

[1 2 3 4 5 6 7 8 9]


In [ ]:
np.arange(30,101,2)

[ 30  32  34  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64
  66  68  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
#np.linspace() fonksiyonuyla da hızlıca arrayler oluşturabilir. 

In [ ]:
np.linspace(30,50,6, dtype=int) #Endpoint bunda dahil 6 tane üye

[30 34 38 42 46 50]


In [ ]:
np.logspace(1,3 ,5)  #10**1 ile 10**3 arasında logaritmik artış yapan 5 tane veriden oluşan bir array oluştur. 

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [ ]:
np.zeros(5, dtype=int)

[0 0 0 0 0]


In [ ]:
np.zeros((2,3), dtype=int)

In [ ]:
np.ones(10, dtype=int)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
np.ones((3,5), dtype=int)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
np.ones((2,3,5),dtype=int)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
np.eye(5, dtype='int') #5x5 brim matris

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#Tüm değerleri aynı olan dizi oluşturma np.full() methodu ile

In [4]:
np.full((4,4),50)

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

Rasgele diziler oluşturma

In [ ]:
#np.random modülünü kullanarak rasgele verilerle arrayler oluşturmak

In [ ]:
np.random.rand(3) #3 tane 0-1 aralığında değerlerden oluşan bir array oluşturur. 

[0.42763297 0.65596049 0.93165992]


In [ ]:
np.random.rand(2,5)

[[0.45396771 0.47620473 0.31871217 0.07881006 0.27935252]
 [0.3443193  0.89525825 0.40171498 0.18882308 0.1124178 ]]


In [ ]:
np.random.rand(3)*10 #3 tane 0-10 aralığında değerlerden oluşan bir array oluştururdu. 

In [ ]:
np.random.randint(15,50,5)

[34 42 48 25 23]


In [ ]:
np.random.randint(0,100,(3,6))

[[ 6 85 96 75 69  1]
 [71 81 35 76 65 63]
 [41  0 80 20 11 49]]


Arrayin Boyut Sayısını ve Shape'ini Kontrol Etmek

In [ ]:
print(arr0d)
print(arr1d)
print(arr2d)
print(arr3d)

53
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [100 200 300]]]


In [ ]:
# .ndim attribute'ı ile arrayimizin kaç boyutlu olduğuna bakabiliriz. 

In [ ]:
arr0d.ndim

0


In [ ]:
arr1d.ndim

1


In [ ]:
arr2d.ndim

2


In [ ]:
arr3d.ndim

3


In [ ]:
# .shape attribute'ı ile arrayin shapeine bakılabilir. 

In [ ]:
arr2d.shape

(2, 3)


In [ ]:
arr3d

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [100 200 300]]]


In [ ]:
arr3d.shape

(2, 2, 3)


Dizi kopyalarken dikkat!!!

In [4]:
matrix=np.random.randint(0,5,(4,4))

In [5]:
matrix

array([[2, 2, 4, 0],
       [3, 4, 3, 1],
       [1, 0, 2, 3],
       [0, 0, 4, 2]])

In [6]:
matrix2=matrix.view()

In [7]:
matrix2

array([[2, 2, 4, 0],
       [3, 4, 3, 1],
       [1, 0, 2, 3],
       [0, 0, 4, 2]])

In [9]:
matrix2[0]=[9,9,9,9]

In [10]:
matrix2

array([[9, 9, 9, 9],
       [3, 4, 3, 1],
       [1, 0, 2, 3],
       [0, 0, 4, 2]])

In [11]:
matrix

array([[9, 9, 9, 9],
       [3, 4, 3, 1],
       [1, 0, 2, 3],
       [0, 0, 4, 2]])

In [ ]:
#view() methodunda yaptığım herhangi bir değişiklik diğerinide etkiler. 

In [5]:
a=np.array([1,2,3])
b=a
b[0]=90

print(a)

[90  2  3]


In [ ]:
#b bir pointer gibi a'nın gösterdiği aynı memory lokasyonunu gösteriyor o nedenle b! deki değişiklik a da da oluyor.
#bu tarz durumlarla karşılaşmamak için copy() fonksiyonunu kullanın:

In [6]:
a=np.array([1,2,3])
b=a.copy()
b[0]=90

print(a)

[1 2 3]


Dosyadan dizi yükleme

In [14]:
filedata = np.genfromtxt('ornek.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 8]
 [3 3 3 5 7 9 0]]


In [15]:
filedata[1,0]

8