    Dizi İşlemleri

In [3]:
#alt başlıklar
#-NumPy Arraylerini indeksleme ve öğelerine Erişme
#-NumPy Arraylerinde Slicing(Dilimleme) Yapılabilir
#-Bir Arrayin Veri Türünü(Data Type'ını) Kontrol Etme
#-Bir Arrayin Dtype'ını Değiştirme 
#-Array Elemanları Arasında 4 işlem
#Evrensel fonksiyonlar (sin, cos, exp, sqrt, log)

In [4]:
import numpy as np

NumPy Arraylerini indeksleme ve öğelerine Erişme

In [12]:
arr1d=([1,2,3,4])
arr2d=([[1,2,3],[4,5,6]])
arr3d=([[[1,2,3],[4,5,6]],[[7,8,9],[100,200,300]]])

In [13]:
arr1d #1 boyutlu arrayler aynı listeler gibi düşünebiliriz. 

[1, 2, 3, 4]

In [ ]:
arr1d[3]

4


In [ ]:
arr2d

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2d[0][2] #arr2d[3,2]

3


In [ ]:
arr3d

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [100 200 300]]]


In [ ]:
arr3d[0,1,2] #arr3d[0][1][2]

6


In [ ]:
arr3d[1][0][-1] #Negatif indexleme burda da var.

9


In [ ]:
arr=np.arange(53,62)
print(arr[4])

57


NumPy Arraylerinde Slicing(Dilimleme) Yapılabilir

In [ ]:
arr=np.arange(50,65)
print(arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


In [ ]:
arr[5:11] #11 dahil deği

[55 56 57 58 59 60]


In [ ]:
arr[-5: ]

[60 61 62 63 64]


In [ ]:
arr[2:10:2]

[52 54 56 58]


In [ ]:
arr[5:11]=999 #Broadcasting
print(arr)

[ 50  51  52  53  54 999 999 999 999 999 999  61  62  63  64]


In [ ]:
arr=np.arange(-30,11)
print(arr[5:19])

[-25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13 -12]


Bir Arrayin Veri Türünü(Data Type'ını) Kontrol Etme

In [ ]:
# .dtype attribute'ı ile arrayimizin data type'ı kontrol edilebilir. 

In [ ]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr.dtype

int32


In [ ]:
arr2=np.arange(100,dtype='float')
print(arr2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [ ]:
arr2.dtype

float64


In [ ]:
arr3=np.array(['a','b','c'])
print(arr3)

['a' 'b' 'c']


In [ ]:
arr3.dtype

<U1


Bir Arrayin Dtype'ını Değiştirme

In [ ]:
arr=np.array([1.2,3.5,5.8])
print(arr)

[1.2 3.5 5.8]


In [ ]:
arr.dtype

float64


In [ ]:
# .astype() methodu ile arraylerin dtype'nı değiştirebilir. 

In [ ]:
arr.astype('int')

[1 3 5]


In [ ]:
arr=np.array(['5','7','19','1','22','99','4'])

In [ ]:
arr.astype('int')


[ 5  7 19  1 22 99  4]


Array Elemanları Arasında 4 işlem

In [ ]:
arr1 =np.array([10,20,50,100])
arr2 =np.array([5,7,9,1])

In [ ]:
arr1

[ 10  20  50 100]


In [ ]:
arr2

[5 7 9 1]


In [ ]:
arr1+arr2

[ 15  27  59 101]


In [ ]:
arr1.__add__(arr2)

[ 15  27  59 101]


In [ ]:
arr1-arr2 #__sub__()

[ 5 13 41 99]


In [ ]:
arr1*arr2

[ 50 140 450 100]


In [ ]:
arr1**arr2

[    100000 1280000000 1507045888        100]


In [ ]:
arr1/arr2

[  2.           2.85714286   5.55555556 100.        ]


In [ ]:
arr2//arr2

[1 1 1 1]


Evrensel fonksiyonlar (sin, cos, exp, sqrt, log)

In [ ]:
#np.sin, radian cinsinden sinüs değerlerini döndürür.
#np.sqrt, elemanların karekökünü alır.
#np.log, doğal logaritmayı hesaplar.

In [14]:
array = np.array([0, np.pi/2, np.pi])

In [6]:
sin_values = np.sin(array)
sqrt_values = np.sqrt(np.array([1, 4, 9]))
log_values = np.log(np.array([1, np.e, np.e**2]))

print("Sinüs değerleri:", sin_values)
print("Karekök değerleri:", sqrt_values)
print("Logaritma değerleri:", log_values)


Sinüs değerleri: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Karekök değerleri: [1. 2. 3.]
Logaritma değerleri: [0. 1. 2.]
