    Dizi Manipülasyonu

In [8]:
#alt başlıklar
#-Bir Array'i Reshape(yeniden şekillendirme) Etme
#Arrayleri Düzleştirme(Flatten)
#-Dizi birleştirme ve ayırma ( concatenate , split ).
#-Diziye yeni boyut ekleme ( np.newaxis ).

In [2]:
import numpy as np

Bir Array'i Reshape(yeniden şekillendirme) Etme

In [10]:
# .reshape() metodu arrayin şeklini değiştirmeye yarar.
# .reshape() yaparken toplam eleman sayısını sabit tutmaya dikkat edilmeli.

In [11]:
arr3d=np.array([[[1,2,3],[4,5,6],[10,25,35],[40,50,60]],[[10,20,30],[5,10,20],[11,22,33],[44,55,66]]])

In [12]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [13]:
arr3d.shape

(2, 4, 3)

In [14]:
arr2d=arr3d.reshape(2,12)
print(arr2d)

[[ 1  2  3  4  5  6 10 25 35 40 50 60]
 [10 20 30  5 10 20 11 22 33 44 55 66]]


In [15]:
arr=np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
arr2d=arr.reshape(4,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
arr3d=np.arange(30).reshape(2,3,5)
print(arr3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [18]:
#Bilinmeyen Boyut!
# .reshape() methodu kullanılırken hesaplamak istediğimiz boyut yerine -1 yazıp otomatik hesaplattırabiliriz.

In [19]:
arr3d=np.arange(120).reshape(5,2,-1)
print(arr3d)

[[[  0   1   2   3   4   5   6   7   8   9  10  11]
  [ 12  13  14  15  16  17  18  19  20  21  22  23]]

 [[ 24  25  26  27  28  29  30  31  32  33  34  35]
  [ 36  37  38  39  40  41  42  43  44  45  46  47]]

 [[ 48  49  50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69  70  71]]

 [[ 72  73  74  75  76  77  78  79  80  81  82  83]
  [ 84  85  86  87  88  89  90  91  92  93  94  95]]

 [[ 96  97  98  99 100 101 102 103 104 105 106 107]
  [108 109 110 111 112 113 114 115 116 117 118 119]]]


In [20]:
arr=np.arange(60).reshape(2,-1,5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


Arrayleri Düzleştirme(Flatten)

In [21]:
#Düzleştirme işlemi(Flatten) çok boyutlu bir array'i 1 boyutlu hale döndürmeye denir. 
# Basitçe .reshape(-1)

In [22]:
arr2d=np.arange(40).reshape(8,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [23]:
arr2d.shape

(8, 5)

In [24]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [25]:
arr3d=np.arange(60).reshape(-1,5,4)
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]]


In [26]:
arr3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

NumPy Arraylerin Birleştirme(Concatenate)

In [27]:
#Numpy Arraylerini birleştirme işlemi .concatenate() fonsiyonu ile yapılır. Fonsiyonun içine liste halinde birleştirilecek arrayler verilir. 
# np.concatenate([arr1,arr2],axis=1)

In [28]:
arr1=np.array([10,20,30,70])
arr2=np.array([100,200,600,900])

In [29]:
arr1

array([10, 20, 30, 70])

In [30]:
arr2

array([100, 200, 600, 900])

In [31]:
np.concatenate([arr1,arr2],axis=0)

array([ 10,  20,  30,  70, 100, 200, 600, 900])

In [32]:
arr1=np.array([[1,2,3],[5,6,7]])
arr2=np.array([[100,200,300],[700,800,900]])

In [43]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [34]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [35]:
np.concatenate([arr1,arr2],axis=0) #satır bazlı birleştirme

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [36]:
np.concatenate([arr1,arr2],axis=1) #sütun sütun birleştirme

array([[  1,   2,   3, 100, 200, 300],
       [  5,   6,   7, 700, 800, 900]])

NumPy Arraylerin Ayırma(split)

In [ ]:
#np.split, verilen diziyi eşit büyüklükte parçalara böler. Eğer dizi, istenen parçalara tam bölünemiyorsa hata alırsınız. 

In [7]:
array = np.arange(9)
print(array)

[0 1 2 3 4 5 6 7 8]


In [8]:
split_arrays = np.split(array, 3)
print(split_arrays)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Arrayleri Stackleme(Yığınlama) işlemleri

In [37]:
#concatenate işleminin hemen hemen aynıdır tek farkı yeni bir boyut(eksen) üzerinde yığınlamalar yapmasıdır. 

In [38]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [39]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [40]:
np.concatenate([arr1,arr2],axis=0) #2d kalıyor

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [41]:
np.stack([arr1,arr2],axis=0) #3d oluyor

array([[[  1,   2,   3],
        [  5,   6,   7]],

       [[100, 200, 300],
        [700, 800, 900]]])

In [42]:
#np.hstack() -->satır boyunca yığınlama
#np.vstack() -->sütun boyunca yığınlama

Diziye yeni boyut ekleme ( np.newaxis )

In [4]:
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [5]:
array_2d = array[:, np.newaxis]
print(array_2d)

[[1]
 [2]
 [3]]
