    İstatistiksel ve Matematiksel Fonksiyonlar


In [ ]:
#altbaşlıklar
#-Bir Arrayin Toplamına/Ortalamasına/Varyansına/Standart Sapmasına Bakma
#-NumPy Dizilerde Maximum-Minimum Elemanlarına ve bu Elemenaların İndexlerine
#-Matris çarpımı ( np.dot , @ operatörü).

In [2]:
import numpy as np

Bir Arrayin Toplamına/Ortalamasına/Varyansına/Standart Sapmasına Bakma

In [ ]:
arr=np.random.randint(0,10,10)

In [ ]:
arr

[7 4 1 2 6 4 8 3 7 9]


In [ ]:
arr.sum()

51


In [ ]:
arr.mean()

5.1


In [ ]:
arr.var() #varyansın büyük olması verilerin ayrıştığı yani çok büyük sayıarda var çok küçük sayılarda var

6.49


In [ ]:
arr.std() #mean ile karşılaştır

2.5475478405713994


In [ ]:
np.sqrt(arr)

[2.64575131 2.         1.         1.41421356 2.44948974 2.
 2.82842712 1.73205081 2.64575131 3.        ]


NumPy Dizilerde Maximum-Minimum Elemanlarına ve bu Elemenaların İndexlerine

In [ ]:
arr=np.random.randint(1,100,10)
print(arr)

[28 48 23 53 20 80 27 67 51 94]


In [ ]:
arr.max()

94


In [ ]:
arr.argmax() #max'ın bulunduğu index

9


In [ ]:
arr.min()

20


In [ ]:
arr.argmin() #min'in bulunduğu index

4


Matris çarpımı ( np.dot , @ operatörü).

In [ ]:
#np.dot ve @, matris çarpımı yapar. Her ikisi de aynı sonucu döndürür.

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[2 0]
 [1 3]]


In [5]:
dot_product = np.dot(A, B)
print(dot_product)

[[ 4  6]
 [10 12]]


In [6]:
at_operator = A @ B
print(at_operator)

[[ 4  6]
 [10 12]]
