    Boolean Diziler ve Filtreleme

In [ ]:
#altbaşlıklar
#-Koşullu işlemler ( array > 5 , array == 0 ).
#-Boolean dizilerle eleman seçimi.
#-np.where ile koşullu seçim.

In [1]:
import numpy as np

Koşullu işlemler

In [8]:
matrix=np.random.randint(0,5,(4,4))

In [9]:
matrix

array([[0, 4, 4, 2],
       [3, 3, 1, 3],
       [1, 4, 3, 4],
       [4, 2, 1, 2]])

In [10]:
matrix>5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#Koşullu ifadelerle bir dizide belirli bir kriteri sağlayan elemanları seçebilirsiniz.

In [2]:
array = np.array([1, 4, 6, 8, 3, 9, 5, 2, 7, 10])
print(array)

[ 1  4  6  8  3  9  5  2  7 10]


In [3]:
filtered_array = array[array > 5]
print(filtered_array)

[ 6  8  9  7 10]


In [4]:
filtered_array = array[array==0]
print(filtered_array)

[]


Boolean Dizilerle Eleman Seçimi

In [5]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array)

[1 2 3 4 5 6 7 8]


In [6]:
is_even = array % 2 == 0
even_numbers = array[is_even]
print(even_numbers)

[2 4 6 8]


In [7]:
is_odd = array % 2 == 1
odd_numbers = array[is_odd]
print(odd_numbers)

[1 3 5 7]


NumPy Arraylerinde Arama

In [ ]:
#Aradığımız değerlerin bulunduğu indexleri döndürmek için np.where() fonsiyonunu kullanırız. 
#np.where() içerisinde argüman olarak condition(şart) alır.

In [ ]:
arr=np.array([1,2,5,6,7,7,9,2,2,2])

In [ ]:
arr

[1 2 5 6 7 7 9 2 2 2]


In [ ]:
np.where(arr==9) #Arrayimizin kaçıncı indeksindeki elemanlar 9'dur?

(array([6], dtype=int64),)


In [ ]:
np.where(arr==2)

(array([1, 7, 8, 9], dtype=int64),)


In [ ]:
np.where(arr%2!=0)

(array([0, 2, 4, 5, 6], dtype=int64),)
