    Matrisler ve Lineer Cebir

In [ ]:
#altbaşlıklar
#-Matris oluşturma ve işlemler.
#-Matris transpozesi ( .T ).
#-Determinant ve ters matris hesaplama ( np.linalg.det , np.linalg.inv).
#-Matris slice

In [1]:
import numpy as np

Matris Oluşturma ve İşlemler

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [30]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
np.diag([1,2,3,2,1])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [34]:
r=np.random.randint(0,3,(5,5))
print(r)

[[1 1 1 1 0]
 [2 2 2 1 1]
 [1 1 0 2 1]
 [2 2 0 1 0]
 [2 1 2 1 1]]


In [35]:
np.diag(r)

array([1, 2, 0, 1, 1])

In [36]:
np.diag(np.diag(r))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [2]:
identity_matrix = np.eye(2)
print( identity_matrix)

[[1. 0.]
 [0. 1.]]


In [3]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


In [6]:
result = identity_matrix + matrix
print(result)

[[2. 2.]
 [3. 5.]]


In [ ]:
#np.eye, birim matris oluşturur. Matris toplama, eleman bazında yapılır.

Matris Transpozesi

In [ ]:
#.T özelliği, bir matrisin satır ve sütunlarını yer değiştirir.

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [8]:
transposed = matrix.T
print(transposed)


[[1 4]
 [2 5]
 [3 6]]


Determinant ve Ters Matris Hesaplama

In [ ]:
#np.linalg.det, matrisin determinantını hesaplar. 
#Determinant sıfırdan farklıysa np.linalg.inv ile tersini alabilirsiniz.

In [9]:
matrix = np.array([[4, 7], [2, 6]])
print(matrix)

[[4 7]
 [2 6]]


In [10]:
det = np.linalg.det(matrix)
print(det)

10.000000000000002


In [11]:
inverse = np.linalg.inv(matrix)
print(inverse)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
#ya sıfır olursa

In [15]:
matrix = np.array([[4, 12], [2, 6]])
print(matrix)

[[ 4 12]
 [ 2  6]]


In [16]:
det = np.linalg.det(matrix)
print(det)

0.0


In [ ]:
inverse = np.linalg.inv(matrix)
print(inverse)
#LinAlgError: Singular matrix

In [22]:
#bu yüzden if kontrolü eklenebilir
if(det==0):
    print("tersi alinamaz")
else:
    inverse = np.linalg.inv(matrix)
    print(inverse)

tersi alinamaz


Matris slice

In [23]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [24]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
matrix[0]

array([1, 2, 3, 4])

In [25]:
matrix[0:4,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [26]:
matrix[1:3,1:3]

array([[ 6,  7],
       [10, 11]])