    Rastgele Sayılar ve NumPy

In [ ]:
#altbaşlıklar
#-Rastgele dizi oluşturma ( np.random modülü).
#-Rastgele sayıların kontrolü (seed).

In [1]:
import numpy as np

NumPy'da Random Kütüphanesi

In [ ]:
#Random diye ayrı bir kütüphane olmasının yanı sıra NumPy kütüphanesinin içinde random adında bir modül de bulunur.
#NumPy'ın içindeki random modülü normal random kütüphanesinden daha kapsamlıdır.

In [ ]:
# from numpy import random as rd
import numpy as np

In [ ]:
np.random.rand() #0-1 arası 1 tane sayı döndürür. 

0.172890058328245


In [ ]:
np.random.randn(5) #normal dağılımdan random 5 tane veri çek

[-1.38636323  0.68311636  0.30161922  2.36888026 -0.93969477]


In [ ]:
np.random.randint(low=10,high=30,size=5)

[16 26 28 27 10]


In [ ]:
np.random.randint(10,30,5)

[18 29 23 27 21]


In [ ]:
arr

[1 2 5 6 7 7 9 2 2 2]


In [ ]:
np.random.choice(arr)

2


In [ ]:
np.random.choice([3,-1,15])

15


Rastgele sayıların kontrolü (seed).

In [ ]:
#np.random.seed ile rastgele sayı üretimi kontrol edilir. Aynı seed değeriyle her çalıştırmada aynı rastgele sayılar üretilir.

In [5]:
np.random.seed(42)
random_array = np.random.rand(3, 3)
print(random_array)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [11]:
np.random.seed(0)
random1 = np.random.rand(3)
print(random1)

[0.5488135  0.71518937 0.60276338]


In [10]:
np.random.seed(0)
random2 = np.random.rand(3)
print(random2)

[0.5488135  0.71518937 0.60276338]


In [12]:
print(np.array_equal(random1, random2))

True
