In [3]:
#altbaşlıklar
#Çok Boyutlu Arraylerde Iteration(yineleme)
#Çok Boyutlu Arraylerde nditer() kullanımı

In [4]:
import numpy as np

Çok Boyutlu Arraylerde Iteration(yineleme)

In [15]:
arr1d=np.arange(10)
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
for x in arr1d:
    print(x)

0
1
2
3
4
5
6
7
8
9


In [7]:
arr2d=np.arange(20).reshape(4,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
for x in arr2d:
    print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [9]:
for x in arr2d:
    for y in x:
        print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [10]:
arr3d=np.arange(30).reshape(-1,3,5)
print(arr3d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [11]:
for x in arr3d:
    for y in x:
        for z in y:
            print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


Çok Boyutlu Arraylerde nditer() kullanımı

In [12]:
#For döngüsü arrayin boyutu kadar sayıda kullanılırsa ancak array'in bütün elemanlarına tek tek erişebiliriz.
#Çok boyutlu arraylerde nditer() fonksiyonu bunun için geliştirilmiştir. 
#For döngüsüne çok daha efektif ve hızlı bir şekilde tüm elemanları dönmenizi sağar. 

In [13]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [14]:
for x in np.nditer(arr3d):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
